/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as sssSol from "./SSS.sol";
export type { sssSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ERC20 } from "./ERC20";
