/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControlDefaultAdminRules } from "./AccessControlDefaultAdminRules";
export type { AccessControlEnumerable } from "./AccessControlEnumerable";
export type { IAccessControlDefaultAdminRules } from "./IAccessControlDefaultAdminRules";
export type { IAccessControlEnumerable } from "./IAccessControlEnumerable";
